---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Consulta le opzioni di configurazione disponibili per le configurazioni di Astra Trident. 
---
= Opzioni di configurazione dello storage
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consulta le opzioni di configurazione disponibili per le configurazioni di Astra Trident.



== Opzioni di configurazione globale

Queste opzioni di configurazione si applicano a tutte le configurazioni Astra Trident, indipendentemente dalla piattaforma di storage utilizzata.

[cols="3*"]
|===
| Opzione | Descrizione | Esempio 


| `version`  a| 
Numero di versione del file di configurazione
 a| 
`1`



| `storageDriverName`  a| 
Nome del driver di storage
 a| 
`ontap-nas`, , `ontap-san`, , `ontap-nas-economy`,
`ontap-nas-flexgroup` `solidfire-san`



| `storagePrefix`  a| 
Prefisso opzionale per i nomi dei volumi. Predefinito: `netappdvp_`.
 a| 
`staging_`



| `limitVolumeSize`  a| 
Restrizione opzionale sulle dimensioni dei volumi. Predefinito: "" (non applicato)
 a| 
`10g`

|===

TIP: Non utilizzare `storagePrefix` (incluso il valore predefinito) per i backend dell'elemento. Per impostazione predefinita, il `solidfire-san` driver ignora questa impostazione e non utilizza un prefisso. Si consiglia di utilizzare un tenantId specifico per la mappatura dei volumi Docker o i dati degli attributi che vengono popolati con la versione Docker, le informazioni sul driver e il nome raw di Docker nei casi in cui sia stato utilizzato il comando dei nomi.

Sono disponibili opzioni predefinite per evitare di doverle specificare su ogni volume creato. L' `size`opzione è disponibile per tutti i tipi di controller. Consultare la sezione relativa alla configurazione di ONTAP per un esempio su come impostare le dimensioni predefinite del volume.

[cols="3*"]
|===
| Opzione | Descrizione | Esempio 


| `size`  a| 
Dimensione predefinita opzionale per i nuovi volumi. Predefinito: `1G`
 a| 
`10G`

|===


== Configurazione ONTAP

Oltre ai valori di configurazione globali sopra indicati, quando si utilizza ONTAP, sono disponibili le seguenti opzioni di primo livello.

[cols="3*"]
|===
| Opzione | Descrizione | Esempio 


| `managementLIF`  a| 
Indirizzo IP della LIF di gestione ONTAP. È possibile specificare un nome di dominio completo (FQDN).
 a| 
`10.0.0.1`



| `dataLIF`  a| 
Indirizzo IP del protocollo LIF.

*Driver NAS ONTAP*: Si consiglia di specificare `dataLIF`. Se non fornito, Astra Trident recupera i dati LIF dalla SVM. È possibile specificare un FQDN (Fully-qualified domain name) da utilizzare per le operazioni di montaggio NFS, consentendo di creare un DNS round-robin per il bilanciamento del carico tra più LIF di dati.

*Driver SAN ONTAP*: Non specificare iSCSI. Astra Trident utilizza link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mappa LUN selettiva ONTAP"^] per scoprire le LIF di isci necessarie per stabilire una sessione multi-path. Viene generato un avviso se `dataLIF` è definito esplicitamente.
 a| 
`10.0.0.2`



| `svm`  a| 
Macchina virtuale per lo storage da utilizzare (obbligatorio, se la LIF di gestione è una LIF del cluster)
 a| 
`svm_nfs`



| `username`  a| 
Nome utente per la connessione al dispositivo di storage
 a| 
`vsadmin`



| `password`  a| 
Password per la connessione al dispositivo di storage
 a| 
`secret`



| `aggregate`  a| 
Aggregato per il provisioning (facoltativo; se impostato, deve essere assegnato alla SVM). Per il `ontap-nas-flexgroup` driver, questa opzione viene ignorata. Tutti gli aggregati assegnati alla SVM vengono utilizzati per il provisioning di un volume FlexGroup.
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Facoltativo, non eseguire il provisioning se l'utilizzo è superiore a questa percentuale
 a| 
`75%`



| `nfsMountOptions`  a| 
Controllo dettagliato delle opzioni di montaggio NFS; il valore predefinito è "-o nfsvers=3". *Disponibile solo per `ontap-nas` i driver e `ontap-nas-economy`*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Fare clic qui per informazioni sulla configurazione degli host NFS"^].
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Astra Trident crea e gestisce per nodo `igroups` come `netappdvp`.

Questo valore non può essere modificato o omesso.

*Disponibile solo per il `ontap-san` conducente*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Dimensioni massime del volume richiudibile.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Il numero massimo di qtree per FlexVol deve essere compreso nell'intervallo [50, 300], il valore predefinito è 200.

*Per il `ontap-nas-economy` driver, questa opzione consente di personalizzare il numero massimo di qtree per FlexVol*.
 a| 
`300`



| `sanType` | *Supportato solo per `ontap-san` il driver.* Utilizzare questa opzione per selezionare `iscsi` per iSCSI o `nvme` NVMe/TCP. | `iscsi` se vuoto 


| `limitVolumePoolSize` | *Supportato `ontap-san-economy` `ontap-san-economy` solo per i driver e.* Limita le dimensioni degli FlexVol in driver ONTAP ONTAP-nas-Economy e ONTAP-SAN-Economy.  a| 
`300g`

|===
Sono disponibili opzioni predefinite per evitare di doverle specificare su ogni volume creato:

[cols="1,3,2"]
|===
| Opzione | Descrizione | Esempio 


| `spaceReserve`  a| 
Modalità di prenotazione dello spazio; `none` (thin provisioning) o `volume` (thick)
 a| 
`none`



| `snapshotPolicy`  a| 
Criterio snapshot da utilizzare, il valore predefinito è `none`
 a| 
`none`



| `snapshotReserve`  a| 
Snapshot Reserve percent (percentuale riserva snapshot), il valore predefinito è "" per accettare il valore predefinito di ONTAP
 a| 
`10`



| `splitOnClone`  a| 
Dividere un clone dal relativo padre al momento della creazione; l'impostazione predefinita è `false`
 a| 
`false`



| `encryption`  a| 
Abilita la crittografia dei volumi NetApp (NVE) sul nuovo volume; il valore predefinito è `false`. NVE deve essere concesso in licenza e abilitato sul cluster per utilizzare questa opzione.

Se NAE è attivato sul backend, tutti i volumi forniti in Astra Trident saranno abilitati per NAE.

Per ulteriori informazioni, fare riferimento a: link:../trident-reco/security-reco.html["Come funziona Astra Trident con NVE e NAE"].
 a| 
vero



| `unixPermissions`  a| 
Opzione NAS per i volumi NFS con provisioning, valore predefinito: `777`
 a| 
`777`



| `snapshotDir`  a| 
Opzione NAS per l'accesso alla `.snapshot` directory, l'impostazione predefinita è `false`
 a| 
`true`



| `exportPolicy`  a| 
Opzione NAS da utilizzare per la policy di esportazione NFS, valore predefinito: `default`
 a| 
`default`



| `securityStyle`  a| 
Opzione NAS per l'accesso al volume NFS fornito.

NFS supporta `mixed` e `unix` stili di sicurezza. L'impostazione predefinita è `unix`.
 a| 
`unix`



| `fileSystemType`  a| 
Opzione SAN per selezionare il tipo di file system, il valore predefinito è `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
Criterio di tiering da utilizzare, il valore predefinito è `none`; `snapshot-only` per la configurazione pre-ONTAP 9.5 SVM-DR
 a| 
`none`

|===


=== Opzioni di scalabilità

 `ontap-nas`E `ontap-san` crea una ONTAP FlexVol per ogni volume di Docker. ONTAP supporta fino a 1000 FlexVol per nodo cluster con un massimo di 12,000 FlexVol. Se i requisiti del tuo volume Docker rientrano in questa limitazione, il `ontap-nas` driver è la soluzione NAS preferita a causa delle funzionalità aggiuntive offerte da FlexVol, come le snapshot Docker-volume-granulari e il cloning.

Per ottenere un numero maggiore di volumi Docker rispetto a quelli gestibili dai limiti FlexVol, scegli il `ontap-nas-economy` o il `ontap-san-economy` driver.

 `ontap-nas-economy`Il driver crea volumi Docker come qtree ONTAP all'interno di un pool di FlexVol gestiti automaticamente. I qtree offrono una scalabilità di gran lunga superiore, fino a 100,000 per nodo cluster e 2,400,000 per cluster, a scapito di alcune funzionalità. Il `ontap-nas-economy` driver non supporta le snapshot o il cloning granulari del volume di Docker.


NOTE: Al momento il `ontap-nas-economy` driver non è supportato in Docker Swarm, poiché Swarm non orchestra la creazione di un volume su più nodi.

 `ontap-san-economy`Il driver crea volumi Docker come LUN ONTAP all'interno di un pool condiviso di FlexVol gestiti automaticamente. In questo modo, ogni FlexVol non è limitato a un solo LUN e offre una migliore scalabilità per i carichi di lavoro SAN. A seconda dello storage array, ONTAP supporta fino a 16384 LUN per cluster. Poiché i volumi sono LUN sottostanti, questo driver supporta snapshot e cloning Docker-volume-granulare.

Scegliere il `ontap-nas-flexgroup` driver per aumentare il parallelismo a un singolo volume che può raggiungere l'intervallo di petabyte con miliardi di file. Alcuni casi di utilizzo ideali per FlexGroups includono ai/ML/DL, big data e analytics, build software, streaming, repository di file e così via. Trident utilizza tutti gli aggregati assegnati a una SVM durante il provisioning di un volume FlexGroup. Il supporto di FlexGroup in Trident ha anche le seguenti considerazioni:

* Richiede ONTAP versione 9.2 o successiva.
* Al momento della stesura del presente documento, FlexGroups supporta solo NFS v3.
* Si consiglia di attivare gli identificatori NFSv3 a 64 bit per SVM.
* Le dimensioni minime consigliate per il membro/volume FlexGroup sono 100GiB.
* La clonazione non è supportata per i volumi FlexGroup.


Per informazioni sui gruppi flessibili e sui carichi di lavoro appropriati per i gruppi flessibili, vedere la https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["Guida all'implementazione e alle Best practice per i volumi NetApp FlexGroup"^].

Per ottenere funzionalità avanzate e scalabilità elevata nello stesso ambiente, è possibile eseguire più istanze di Docker Volume Plugin, una con e l'altra `ontap-nas-economy` con `ontap-nas` .



=== File di configurazione ONTAP di esempio

.Esempio di NFS per il driver </code> <code> ONTAP-Avantage
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.Esempio NFS per il driver <code> ONTAP-nas-FlexGroup </code>
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.Esempio NFS per il driver </code> <code> ONTAP-nas-economy
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
====
.Esempio di iSCSI per il driver </code> <code> ONTAP-Avantage
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.Esempio NFS per il driver </code> <code> ONTAP-san-economy
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.Esempio NVMe/TCP per driver </code> compatibile con <code> ONTAP
[%collapsible]
====
[listing]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username":"vsadmin",
  "password":"password",
  "sanType": "nvme",
  "useREST": true
}
----
====


== Configurazione del software Element

Oltre ai valori di configurazione globali, quando si utilizza il software Element (NetApp HCI/SolidFire), queste opzioni sono disponibili.

[cols="3*"]
|===
| Opzione | Descrizione | Esempio 


| `Endpoint`  a| 
https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
Porta e indirizzo IP iSCSI
 a| 
10.0.0.7:3260



| `TenantName`  a| 
Tenant SolidFireF da utilizzare (creato se non trovato)
 a| 
`docker`



| `InitiatorIFace`  a| 
Specificare l'interfaccia quando si limita il traffico iSCSI all'interfaccia non predefinita
 a| 
`default`



| `Types`  a| 
Specifiche QoS
 a| 
Vedere l'esempio riportato di seguito



| `LegacyNamePrefix`  a| 
Prefisso per installazioni Trident aggiornate. Se è stata utilizzata una versione di Trident precedente alla 1.3.2 ed è stato eseguito un aggiornamento con volumi esistenti, sarà necessario impostare questo valore per accedere ai vecchi volumi mappati tramite il metodo del nome del volume.
 a| 
`netappdvp-`

|===
Il `solidfire-san` driver non supporta Docker Swarm.



=== Esempio di file di configurazione del software Element

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----