---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Scopri come configurare un backend ONTAP con i driver NAS ONTAP. 
---
= Panoramica del driver NAS ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informazioni sulla configurazione di un backend ONTAP con driver NAS ONTAP e Cloud Volumes ONTAP.



== Dettagli del driver NAS ONTAP

Astra Trident offre i seguenti driver per lo storage NAS per comunicare con il cluster ONTAP. Le modalità di accesso supportate sono: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).


IMPORTANT: Se si utilizza Astra Control per la protezione, il ripristino e la mobilità, leggere <<Compatibilità driver Astra Control>>.

[cols="2, 1, 1, 2, 2"]
|===
| Driver | Protocollo | VolumeMode | Modalità di accesso supportate | File system supportati 


| `ontap-nas`  a| 
SMB CON NFS
 a| 
Filesystem
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`



| `ontap-nas-economy`  a| 
SMB CON NFS
 a| 
Filesystem
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`



| `ontap-nas-flexgroup`  a| 
SMB CON NFS
 a| 
Filesystem
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`

|===


=== Compatibilità driver Astra Control

Astra Control offre protezione, disaster recovery e mobilità perfette (spostando volumi tra i cluster Kubernetes) per i volumi creati con `ontap-nas` , `ontap-nas-flexgroup` e `ontap-san` driver. Per ulteriori informazioni, fare riferimento alla link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Prerequisiti per la replica di Astra Control"^] sezione.

[WARNING]
====
* Utilizzare `ontap-san-economy` solo se si prevede che il conteggio dell'utilizzo persistente del volume sia superiore a link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limiti di volume ONTAP supportati"^].
* Utilizzare `ontap-nas-economy` solo se si prevede che il conteggio dell'utilizzo del volume persistente sia superiore a link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limiti di volume ONTAP supportati"^] e che il `ontap-san-economy` driver non possa essere utilizzato.
* Non utilizzare `ontap-nas-economy` se si prevede la necessità di protezione dei dati, ripristino di emergenza o mobilità.


====


== Autorizzazioni utente

Astra Trident si aspetta di essere eseguito come amministratore di ONTAP o SVM, in genere utilizzando l' `admin`utente del cluster o `vsadmin` un utente SVM o un utente con un nome diverso che svolge lo stesso ruolo.

Per le implementazioni di Amazon FSX per NetApp ONTAP, Astra Trident si aspetta di essere eseguito come amministratore di ONTAP o SVM, utilizzando l'utente del cluster `fsxadmin`, un `vsadmin` utente SVM o un utente con un nome diverso che abbia lo stesso ruolo. L' `fsxadmin`utente sostituisce in modo limitato l'utente amministratore del cluster.


NOTE: Se si utilizza il `limitAggregateUsage` parametro, sono necessarie le autorizzazioni di amministratore del cluster. Quando si utilizza Amazon FSX per NetApp ONTAP con Astra Trident, il `limitAggregateUsage` parametro non funziona con `vsadmin` gli account utente e. `fsxadmin` L'operazione di configurazione non riesce se si specifica questo parametro.

Sebbene sia possibile creare un ruolo più restrittivo all'interno di ONTAP che un driver Trident può utilizzare, non lo consigliamo. La maggior parte delle nuove release di Trident chiamerà API aggiuntive che dovrebbero essere considerate, rendendo gli aggiornamenti difficili e soggetti a errori.
