---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Scopri come configurare un backend ONTAP con i driver SAN ONTAP. 
---
= Panoramica del driver SAN ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informazioni sulla configurazione di un backend ONTAP con driver SAN ONTAP e Cloud Volumes ONTAP.



== Dettagli del driver SAN ONTAP

Astra Trident offre i seguenti driver per lo storage SAN per comunicare con il cluster ONTAP. Le modalità di accesso supportate sono: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).


IMPORTANT: Se si utilizza Astra Control per la protezione, il ripristino e la mobilità, leggere <<Compatibilità driver Astra Control>>.

[cols="2, 1, 1, 2, 2"]
|===
| Driver | Protocollo | VolumeMode | Modalità di accesso supportate | File system supportati 


| `ontap-san`  a| 
ISCSI
 a| 
Blocco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Nessun file system; dispositivo a blocchi raw



| `ontap-san`  a| 
ISCSI
 a| 
Filesystem
 a| 
RWO, RWOP

ROX e RWX non sono disponibili in modalità Volume filesystem.
 a| 
`xfs`, , `ext3` `ext4`



| `ontap-san`  a| 
NVMe/TCP

Fare riferimento alla <<Considerazioni aggiuntive su NVMe/TCP>>.
 a| 
Blocco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Nessun file system; dispositivo a blocchi raw



| `ontap-san`  a| 
NVMe/TCP

Fare riferimento alla <<Considerazioni aggiuntive su NVMe/TCP>>.
 a| 
Filesystem
 a| 
RWO, RWOP

ROX e RWX non sono disponibili in modalità Volume filesystem.
 a| 
`xfs`, , `ext3` `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Blocco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Nessun file system; dispositivo a blocchi raw



| `ontap-san-economy`  a| 
ISCSI
 a| 
Filesystem
 a| 
RWO, RWOP

ROX e RWX non sono disponibili in modalità Volume filesystem.
 a| 
`xfs`, , `ext3` `ext4`

|===


=== Compatibilità driver Astra Control

Astra Control offre protezione, disaster recovery e mobilità perfette (spostando volumi tra i cluster Kubernetes) per i volumi creati con `ontap-nas` , `ontap-nas-flexgroup` e `ontap-san` driver. Per ulteriori informazioni, fare riferimento alla link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Prerequisiti per la replica di Astra Control"^] sezione.

[WARNING]
====
* Utilizzare `ontap-san-economy` solo se si prevede che il conteggio dell'utilizzo persistente del volume sia superiore a link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limiti di volume ONTAP supportati"^].
* Utilizzare `ontap-nas-economy` solo se si prevede che il conteggio dell'utilizzo del volume persistente sia superiore a link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limiti di volume ONTAP supportati"^] e che il `ontap-san-economy` driver non possa essere utilizzato.
* Non utilizzare `ontap-nas-economy` se si prevede la necessità di protezione dei dati, ripristino di emergenza o mobilità.


====


== Autorizzazioni utente

Astra Trident si aspetta di essere eseguito come amministratore di ONTAP o SVM, in genere utilizzando l' `admin`utente del cluster o `vsadmin` un utente SVM o un utente con un nome diverso che svolge lo stesso ruolo. Per le implementazioni di Amazon FSX per NetApp ONTAP, Astra Trident si aspetta di essere eseguito come amministratore di ONTAP o SVM, utilizzando l'utente del cluster `fsxadmin`, un `vsadmin` utente SVM o un utente con un nome diverso che abbia lo stesso ruolo. L' `fsxadmin`utente sostituisce in modo limitato l'utente amministratore del cluster.


NOTE: Se si utilizza il `limitAggregateUsage` parametro, sono necessarie le autorizzazioni di amministratore del cluster. Quando si utilizza Amazon FSX per NetApp ONTAP con Astra Trident, il `limitAggregateUsage` parametro non funziona con `vsadmin` gli account utente e. `fsxadmin` L'operazione di configurazione non riesce se si specifica questo parametro.

Sebbene sia possibile creare un ruolo più restrittivo all'interno di ONTAP che un driver Trident può utilizzare, non lo consigliamo. La maggior parte delle nuove release di Trident chiamerà API aggiuntive che dovrebbero essere considerate, rendendo gli aggiornamenti difficili e soggetti a errori.



== Considerazioni aggiuntive su NVMe/TCP

Astra Trident supporta il protocollo non-volatile memory express (NVMe) utilizzando il `ontap-san` driver, tra cui:

* IPv6
* Snapshot e cloni di volumi NVMe
* Ridimensionamento di un volume NVMe
* Importare un volume NVMe creato al di fuori di Astra Trident in modo che il suo ciclo di vita possa essere gestito da Astra Trident
* Multipath nativo NVMe
* Arresto anomalo o anomalo dei K8s nodi (24,06)


Astra Trident non supporta:

* DH-HMAC-CHAP supportato nativamente da NVMe
* Multipathing DM (Device mapper)
* Crittografia LUKS

